import { db } from '@/db';
import { chatbotKnowledge } from '@/db/schema';

async function main() {
    const sampleKnowledge = [
        {
            category: 'ministry_info',
            question: 'What is the mission of UCon Ministries?',
            answer: 'UCon Ministries exists to meet individuals at their point of need, offering immediate practical assistance and guiding them through a comprehensive journey of healing and transformation. Our mission is to transform feelings of worthlessness and mental health struggles into enduring purpose and dignity for those deeply impacted by the justice system, addiction, homelessness, and personal brokenness. We walk alongside each person, helping them discover that their past can become their purpose.',
            keywords: 'mission, purpose, transformation, healing, justice system, addiction, homelessness, mental health, dignity, worthlessness',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            category: 'ministry_info',
            question: 'What is the UCon Ministries slogan?',
            answer: 'Our slogan is "Where Your Past Becomes Your Purpose." This reflects our core belief that no matter what you have been through, God can transform your story into a testimony that brings hope and healing to others. Your struggles can become your strength, and your wounds can become your wisdom.',
            keywords: 'slogan, past, purpose, transformation, hope, testimony, strength, wisdom',
            createdAt: new Date('2024-12-02').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        },
        {
            category: 'ministry_info',
            question: 'What is the vision of UCon Ministries?',
            answer: 'Our vision is to create a community where every person experiences radical transformation through Christ-centered care, practical support, and leadership development. We envision a world where those who have been broken by life circumstances become pillars of hope in their communities, leading others toward healing and purpose.',
            keywords: 'vision, transformation, Christ-centered, community, leadership, hope, healing',
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },
        {
            category: 'ministry_info',
            question: 'What are the core values of UCon Ministries?',
            answer: 'Our core values are: Compassion - meeting people where they are with Christ\'s love; Dignity - recognizing the inherent worth of every individual; Transformation - believing in the power of God to change lives; Community - creating belonging for the isolated; and Excellence - providing the highest quality care and support in all we do.',
            keywords: 'values, compassion, dignity, transformation, community, excellence, Christ, love, worth',
            createdAt: new Date('2024-12-04').toISOString(),
            updatedAt: new Date('2024-12-04').toISOString(),
        },
        {
            category: 'ministry_info',
            question: 'What is the three-track model at UCon Ministries?',
            answer: 'Our three-track model provides comprehensive support: Track 1 is our Leadership Development Institute (LDI), a 64-week intensive program for deep transformation. Track 2 offers Open Ministry Services including workshops, Bible studies, and pastoral care for community members. Track 3 is Outreach & Community Advocacy, providing immediate practical assistance like transportation, food, and shelter resources.',
            keywords: 'three-track model, LDI, workshops, outreach, Bible study, pastoral care, community, assistance',
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            category: 'programs',
            question: 'What is the Leadership Development Institute (LDI)?',
            answer: 'The Leadership Development Institute is our flagship 64-week residential program designed to bring complete transformation. Participants live on-site and progress through four tiers: Ascension, Pinnacle, Apex, and UCon. Each tier builds upon the previous, moving from personal healing and foundation-building to mentorship development, systemic leadership, and finally visionary leadership that impacts communities.',
            keywords: 'LDI, Leadership Development Institute, 64-week program, residential, transformation, tiers, healing, leadership',
            createdAt: new Date('2024-12-06').toISOString(),
            updatedAt: new Date('2024-12-06').toISOString(),
        },
        {
            category: 'programs',
            question: 'What happens in Tier 1: Ascension of the LDI program?',
            answer: 'Tier 1: Ascension (Weeks 1-16) focuses on building a strong foundation for transformation. Participants work on mental health restoration, spiritual formation, and establishing healthy life rhythms. This tier includes intensive counseling, Biblical teaching, life skills development, and creating a personal healing plan that will guide their journey forward.',
            keywords: 'Tier 1, Ascension, weeks 1-16, foundation, mental health, spiritual formation, counseling, healing',
            createdAt: new Date('2024-12-07').toISOString(),
            updatedAt: new Date('2024-12-07').toISOString(),
        },
        {
            category: 'programs',
            question: 'What happens in Tier 2: Pinnacle of the LDI program?',
            answer: 'Tier 2: Pinnacle (Weeks 17-32) focuses on mentorship development and deepening personal growth. Participants begin serving as peer mentors to newer members while continuing their own healing journey. This tier emphasizes emotional intelligence, conflict resolution, and developing the skills needed to guide and encourage others through their transformation process.',
            keywords: 'Tier 2, Pinnacle, weeks 17-32, mentorship, peer support, emotional intelligence, growth, guidance',
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            category: 'programs',
            question: 'What happens in Tier 3: Apex of the LDI program?',
            answer: 'Tier 3: Apex (Weeks 33-48) develops systemic leadership abilities and community impact skills. Participants learn program development, organizational leadership, and how to create sustainable change in communities. This tier includes training in advocacy, resource management, and leading initiatives that address root causes of social issues.',
            keywords: 'Tier 3, Apex, weeks 33-48, systemic leadership, community impact, advocacy, program development',
            createdAt: new Date('2024-12-09').toISOString(),
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            category: 'programs',
            question: 'What happens in Tier 4: UCon of the LDI program?',
            answer: 'Tier 4: UCon (Weeks 49-64) cultivates visionary leadership and prepares participants to launch their own ministries or initiatives. Participants develop strategic planning skills, learn fundraising and nonprofit management, and create comprehensive plans for their future ministry work. Graduation from this tier represents complete transformation and readiness to lead others toward hope.',
            keywords: 'Tier 4, UCon, weeks 49-64, visionary leadership, ministry launch, strategic planning, graduation',
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            category: 'programs',
            question: 'What are Open Ministry Services?',
            answer: 'Open Ministry Services are free programs available to anyone in the community, regardless of LDI participation. These include weekly Bible studies, rotating workshops on practical life skills, pastoral counseling, one-on-one mentoring, and crisis intervention services. These services provide immediate support and connection for those seeking help without requiring a long-term commitment.',
            keywords: 'Open Ministry Services, Bible study, workshops, pastoral counseling, mentoring, crisis intervention, community',
            createdAt: new Date('2024-12-11').toISOString(),
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            category: 'programs',
            question: 'What is Outreach & Community Advocacy?',
            answer: 'Outreach & Community Advocacy provides immediate practical assistance to those in crisis. Services include transportation to essential appointments, coordination of food drives and meal distribution, shelter placement assistance, connections to rehabilitation programs, and advocacy with social service agencies. We meet urgent needs while connecting people to longer-term support systems.',
            keywords: 'outreach, community advocacy, transportation, food drives, shelter, rehabilitation, crisis assistance',
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            category: 'programs',
            question: 'Does UCon Ministries provide housing?',
            answer: 'Yes, we provide full residential housing for all participants enrolled in our Leadership Development Institute (LDI). Housing is included as part of the 64-week program, creating a stable, supportive environment where participants can focus entirely on their healing and transformation. Living on-site also builds deep community and accountability among participants.',
            keywords: 'housing, residential, LDI, accommodation, stable environment, community living',
            createdAt: new Date('2024-12-13').toISOString(),
            updatedAt: new Date('2024-12-13').toISOString(),
        },
        {
            category: 'staff',
            question: 'Who is the Executive Director of UCon Ministries?',
            answer: 'Sarah Thompson serves as our Executive Director, providing visionary leadership and strategic direction for all UCon Ministries programs. With over 15 years of experience in nonprofit leadership and community development, Sarah is passionate about seeing lives transformed and ensuring our ministry has maximum impact in serving those who need hope.',
            keywords: 'Executive Director, Sarah Thompson, leadership, vision, nonprofit, community development',
            createdAt: new Date('2024-12-14').toISOString(),
            updatedAt: new Date('2024-12-14').toISOString(),
        },
        {
            category: 'staff',
            question: 'Who is the Clinical Director?',
            answer: 'Dr. Michael Chen serves as our Clinical Director, overseeing all mental health and clinical services. As a licensed psychologist with expertise in trauma-informed care and addiction recovery, Dr. Chen ensures that our participants receive evidence-based therapeutic support alongside spiritual care, creating a holistic approach to healing and transformation.',
            keywords: 'Clinical Director, Dr. Michael Chen, mental health, therapy, trauma-informed care, addiction recovery',
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
        {
            category: 'staff',
            question: 'Who leads spiritual formation at UCon Ministries?',
            answer: 'Pastor James Wilson serves as our Spiritual Formation Director, guiding the biblical teaching and spiritual development components of all our programs. With a Master of Divinity and years of pastoral experience, Pastor James creates environments where participants can encounter God\'s love, discover their identity in Christ, and grow in their faith journey.',
            keywords: 'Spiritual Formation Director, Pastor James Wilson, biblical teaching, spiritual development, faith, pastoral care',
            createdAt: new Date('2024-12-16').toISOString(),
            updatedAt: new Date('2024-12-16').toISOString(),
        },
        {
            category: 'staff',
            question: 'Who is the LDI Program Director?',
            answer: 'Rachel Martinez serves as our LDI Program Director, overseeing the day-to-day operations of our Leadership Development Institute. Rachel works closely with participants through each tier, coordinating curriculum, mentorship assignments, and ensuring that each person receives personalized support on their transformation journey. Her compassionate leadership creates a culture of hope and excellence.',
            keywords: 'LDI Program Director, Rachel Martinez, program operations, curriculum, mentorship, leadership',
            createdAt: new Date('2024-12-17').toISOString(),
            updatedAt: new Date('2024-12-17').toISOString(),
        },
        {
            category: 'staff',
            question: 'Who coordinates outreach at UCon Ministries?',
            answer: 'David Johnson serves as our Outreach Coordinator, connecting community members with immediate practical assistance and resources. David builds partnerships with local organizations, coordinates community events, and ensures that anyone who reaches out to UCon Ministries receives compassionate care and the help they need, whether through our programs or connections to other services.',
            keywords: 'Outreach Coordinator, David Johnson, community connections, resources, partnerships, assistance',
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            category: 'staff',
            question: 'Who is the Operations Director?',
            answer: 'Jennifer Lee serves as our Operations Director, managing the administrative and operational systems that support all UCon Ministries programs. Jennifer oversees facilities, finances, volunteer coordination, and ensures that our ministry runs efficiently so that staff can focus on serving participants. Her attention to detail and organizational excellence supports our mission of transformation.',
            keywords: 'Operations Director, Jennifer Lee, administration, operations, facilities, volunteer coordination',
            createdAt: new Date('2024-12-19').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            category: 'contact',
            question: 'What is the phone number for UCon Ministries?',
            answer: 'You can reach UCon Ministries at (555) 555-1234 during our regular business hours Monday through Friday, 9:00 AM to 5:00 PM. If you are experiencing a crisis and need immediate support, please call our 24/7 Crisis Hotline at (555) 555-1234. We are here to help and would love to connect with you.',
            keywords: 'phone number, contact, (555) 555-1234, business hours, crisis hotline, call',
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            category: 'contact',
            question: 'What is the email address for UCon Ministries?',
            answer: 'You can email us at info@uconministries.org for general inquiries, program information, volunteer opportunities, or prayer requests. We check our email regularly and will respond to your message within 24-48 hours. For urgent matters, please call our main line or crisis hotline.',
            keywords: 'email, info@uconministries.org, contact, inquiries, information, communication',
            createdAt: new Date('2024-12-21').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            category: 'contact',
            question: 'Is there a 24/7 crisis hotline?',
            answer: 'Yes, our Crisis Hotline is available 24 hours a day, 7 days a week at (555) 555-1234. If you or someone you know is in crisis, experiencing thoughts of self-harm, struggling with addiction, or facing any emergency situation, please call immediately. Trained volunteers and staff are always ready to provide support, prayer, and connection to resources.',
            keywords: 'crisis hotline, 24/7, emergency, (555) 555-1234, support, self-harm, addiction, immediate help',
            createdAt: new Date('2024-12-22').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            category: 'contact',
            question: 'Where is UCon Ministries located?',
            answer: 'UCon Ministries is located at 123 Hope Street, Community Center, CA 90210. Our facility includes administrative offices, meeting spaces for programs and workshops, and residential housing for LDI participants. Visitors are welcome during business hours, and we encourage you to stop by if you would like to learn more about our ministry or tour our facilities.',
            keywords: 'location, address, 123 Hope Street, Community Center, CA 90210, facility, visit',
            createdAt: new Date('2024-12-23').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            category: 'contact',
            question: 'Does UCon Ministries have a website?',
            answer: 'Yes, our website is uconministries.org where you can find detailed information about our programs, staff, upcoming events, and ways to get involved. The website also has online forms for applications, volunteer registration, and prayer requests. You can also read testimonials from participants and stay updated on our community impact.',
            keywords: 'website, uconministries.org, online, information, forms, testimonials, updates',
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            category: 'business_hours',
            question: 'What are the business hours for UCon Ministries?',
            answer: 'Our main office is open Monday through Friday from 9:00 AM to 5:00 PM, and Saturday from 10:00 AM to 2:00 PM. We are closed on Sundays except for our Worship Service at 10:00 AM. However, our Crisis Hotline is available 24/7 for anyone needing immediate support. Feel free to call, email, or visit during our regular hours.',
            keywords: 'business hours, Monday-Friday, 9am-5pm, Saturday, 10am-2pm, office hours, open',
            createdAt: new Date('2024-12-25').toISOString(),
            updatedAt: new Date('2024-12-25').toISOString(),
        },
        {
            category: 'business_hours',
            question: 'Is UCon Ministries open on weekends?',
            answer: 'Yes, we are open on Saturdays from 10:00 AM to 2:00 PM for general inquiries and walk-in support. On Sundays, we host our Worship Service at 10:00 AM which is open to everyone in the community. While our administrative offices are closed on Sundays, our Crisis Hotline remains available 24/7 for anyone in need.',
            keywords: 'weekend hours, Saturday, Sunday, worship service, 10am, open, available',
            createdAt: new Date('2024-12-26').toISOString(),
            updatedAt: new Date('2024-12-26').toISOString(),
        },
        {
            category: 'events',
            question: 'When is the weekly Bible study?',
            answer: 'Our Monday Bible Study meets every Monday evening at 7:00 PM. This is a warm, welcoming environment where we study Scripture together, share testimonies, and support one another in our faith journeys. Whether you are new to the Bible or have been studying for years, you are welcome to join us for fellowship, prayer, and encouragement.',
            keywords: 'Bible study, Monday, 7pm, weekly, Scripture, fellowship, prayer, testimony',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            category: 'events',
            question: 'What workshops are offered on Wednesdays?',
            answer: 'Wednesday Workshops meet at 6:00 PM and feature rotating topics each week designed to build practical life skills and support transformation. Topics include financial literacy, communication skills, anger management, job readiness, healthy relationships, and creative expression. Check our website or call for the current month\'s schedule. All workshops are free and open to the community.',
            keywords: 'Wednesday workshops, 6pm, rotating topics, life skills, free, community, practical training',
            createdAt: new Date('2024-12-02').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        },
        {
            category: 'events',
            question: 'What happens at Friday Fellowship?',
            answer: 'Friday Fellowship meets every Friday at 7:00 PM and is a casual gathering for community connection, encouragement, and fun. We share a meal together, play games, share stories, and build friendships in a relaxed atmosphere. It\'s a perfect opportunity to meet others who understand the journey of transformation and to experience the warmth of Christian community.',
            keywords: 'Friday Fellowship, 7pm, community, connection, meal, games, friendship, casual',
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },
        {
            category: 'events',
            question: 'When is the Sunday worship service?',
            answer: 'Our Sunday Worship Service begins at 10:00 AM and includes Christ-centered worship, encouraging teaching from Scripture, and opportunities for prayer and ministry. Everyone is welcome regardless of church background or where you are in your faith journey. Come as you are and experience God\'s love in a community that values authenticity, hope, and transformation.',
            keywords: 'worship service, Sunday, 10am, church, praise, teaching, prayer, community',
            createdAt: new Date('2024-12-04').toISOString(),
            updatedAt: new Date('2024-12-04').toISOString(),
        },
        {
            category: 'events',
            question: 'Are there monthly community events?',
            answer: 'Yes, we host monthly community outreach events including food distributions, community clean-up days, family fun events, and resource fairs connecting people with local services. These events are open to everyone and provide opportunities to serve, connect, and experience the love of Christ in action. Check our website or social media for upcoming event details.',
            keywords: 'monthly events, community outreach, food distribution, service opportunities, resource fair, family events',
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            category: 'events',
            question: 'When are LDI graduation ceremonies?',
            answer: 'We celebrate quarterly graduation ceremonies as participants complete each tier of the Leadership Development Institute. These ceremonies honor the hard work, growth, and transformation of our participants and allow the community to witness God\'s redemptive work. Graduations are open to family, friends, and supporters. Contact us for the next ceremony date and to learn how to attend.',
            keywords: 'graduation ceremony, quarterly, LDI, celebration, transformation, milestone, community celebration',
            createdAt: new Date('2024-12-06').toISOString(),
            updatedAt: new Date('2024-12-06').toISOString(),
        },
        {
            category: 'workshops',
            question: 'What is covered in the Financial Literacy Workshop?',
            answer: 'Our Financial Literacy Workshop teaches essential money management skills including budgeting, saving strategies, understanding credit, debt reduction, and financial goal setting. We provide practical tools and worksheets that participants can use immediately to take control of their finances. This workshop empowers individuals to break cycles of poverty and build stable financial futures.',
            keywords: 'financial literacy, budgeting, saving, credit, debt, money management, financial planning',
            createdAt: new Date('2024-12-07').toISOString(),
            updatedAt: new Date('2024-12-07').toISOString(),
        },
        {
            category: 'workshops',
            question: 'What is the Communication Skills Workshop about?',
            answer: 'The Communication Skills Workshop focuses on effective verbal and non-verbal communication, active listening, conflict resolution, and expressing emotions in healthy ways. Participants learn how to build stronger relationships, navigate difficult conversations, and communicate with confidence in personal and professional settings. These skills are essential for leadership and life success.',
            keywords: 'communication skills, listening, conflict resolution, relationships, verbal communication, emotional expression',
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            category: 'workshops',
            question: 'What happens in the Creative Expression Workshop?',
            answer: 'The Creative Expression Workshop uses art, writing, music, and other creative mediums as tools for healing and self-discovery. Participants explore their emotions, process trauma, and discover new ways to express their stories through creative outlets. No artistic experience is required—this workshop is about healing through creativity, not perfection. It\'s a powerful way to find your voice and experience freedom.',
            keywords: 'creative expression, art therapy, writing, music, healing, self-discovery, creativity, trauma processing',
            createdAt: new Date('2024-12-09').toISOString(),
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            category: 'workshops',
            question: 'What does the Job Readiness Workshop teach?',
            answer: 'Our Job Readiness Workshop prepares participants for successful employment with training on resume writing, interview skills, professional dress and behavior, workplace expectations, and job search strategies. We also help identify career paths, connect participants with employers who value second chances, and provide ongoing support throughout the job search and employment process.',
            keywords: 'job readiness, employment, resume, interview skills, career, workplace, job search, professional development',
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            category: 'workshops',
            question: 'What is the Anger Management Workshop?',
            answer: 'The Anger Management Workshop teaches healthy ways to understand and manage anger, including identifying triggers, developing coping strategies, and practicing emotional regulation techniques. Participants learn that anger itself is not wrong, but how we express it matters. This workshop provides practical tools for responding to anger in ways that build relationships rather than damage them.',
            keywords: 'anger management, emotional regulation, coping strategies, triggers, healthy expression, self-control',
            createdAt: new Date('2024-12-11').toISOString(),
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            category: 'workshops',
            question: 'What is covered in the Healthy Relationships Workshop?',
            answer: 'The Healthy Relationships Workshop explores boundaries, communication in relationships, identifying unhealthy patterns, building trust, and creating connections that support growth and healing. We discuss relationships with family, friends, romantic partners, and colleagues, providing biblical wisdom and practical skills for nurturing relationships that honor God and promote mutual wellbeing.',
            keywords: 'healthy relationships, boundaries, trust, communication, family, friendship, biblical relationships, connection',
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'What Bible verse speaks about hope for the future?',
            answer: 'Jeremiah 29:11 says, "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope." This powerful promise reminds us that no matter what we have been through, God has good plans for our future. Your past does not define your destiny—God\'s purposes do.',
            keywords: 'hope, future, Jeremiah 29:11, plans, purpose, destiny, God\'s promises, encouragement',
            createdAt: new Date('2024-12-13').toISOString(),
            updatedAt: new Date('2024-12-13').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'Is there a Bible verse about God giving us hope?',
            answer: 'Romans 15:13 declares, "May the God of hope fill you with all joy and peace in believing, so that by the power of the Holy Spirit you may abound in hope." God is called the God of hope because He is the source of all true hope. When we trust Him, the Holy Spirit empowers us to overflow with hope even in difficult circumstances.',
            keywords: 'hope, Romans 15:13, God of hope, joy, peace, Holy Spirit, trust, believing',
            createdAt: new Date('2024-12-14').toISOString(),
            updatedAt: new Date('2024-12-14').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'What does the Bible say about overcoming addiction?',
            answer: '1 Corinthians 10:13 promises, "No temptation has overtaken you that is not common to man. God is faithful, and he will not let you be tempted beyond your ability, but with the temptation he will also provide the way of escape, that you may be able to endure it." Addiction is powerful, but God is more powerful. He always provides a way out, and you are not alone in this battle.',
            keywords: 'addiction, 1 Corinthians 10:13, temptation, overcoming, way of escape, God\'s faithfulness, recovery, deliverance',
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'Is there a Bible verse about new life in Christ?',
            answer: '2 Corinthians 5:17 proclaims, "Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come." This verse is the heart of transformation—when you surrender your life to Christ, you truly become new. Your past mistakes, your old identity, your former way of living all pass away, and God gives you a fresh start filled with purpose and hope.',
            keywords: 'new creation, 2 Corinthians 5:17, transformation, new life, fresh start, identity in Christ, salvation',
            createdAt: new Date('2024-12-16').toISOString(),
            updatedAt: new Date('2024-12-16').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'What Bible verse talks about God\'s purpose for us?',
            answer: 'Ephesians 2:10 reveals, "For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them." You are God\'s masterpiece, created with intention and purpose. Before you were even born, God prepared good works for you to do. Your life has meaning and divine purpose waiting to be discovered and fulfilled.',
            keywords: 'purpose, Ephesians 2:10, workmanship, good works, created, divine purpose, meaning, calling',
            createdAt: new Date('2024-12-17').toISOString(),
            updatedAt: new Date('2024-12-17').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'Does the Bible say God works everything for good?',
            answer: 'Romans 8:28 assures us, "And we know that for those who love God all things work together for good, for those who are called according to his purpose." Even the painful experiences, the mistakes, and the hardships in your life can be woven together by God into something beautiful. This is the heart of our ministry—seeing God transform your past into your purpose.',
            keywords: 'Romans 8:28, work together for good, God\'s purpose, redemption, transformation, painful experiences, hope',
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'What does the Bible say about our worth and value?',
            answer: 'Psalm 139:14 declares, "I praise you, for I am fearfully and wonderfully made. Wonderful are your works; my soul knows it very well." You are not a mistake or worthless—you are fearfully and wonderfully made by a loving Creator. Your value is not determined by your past or your circumstances, but by the fact that you bear the image of God Himself.',
            keywords: 'worth, value, Psalm 139:14, fearfully and wonderfully made, identity, image of God, dignity, self-worth',
            createdAt: new Date('2024-12-19').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'What Bible verse speaks about being made in God\'s image?',
            answer: 'Genesis 1:27 states, "So God created man in his own image, in the image of God he created him; male and female he created them." Being made in God\'s image means you have inherent dignity, worth, and purpose. No matter what you have done or what has been done to you, this truth remains—you bear the image of the Creator of the universe.',
            keywords: 'image of God, Genesis 1:27, dignity, worth, creation, identity, inherent value, imago dei',
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'How does the Bible say we should transform our minds?',
            answer: 'Romans 12:2 instructs, "Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect." Transformation begins in the mind. As we renew our thinking through God\'s Word and His truth, our lives are transformed from the inside out.',
            keywords: 'transformation, Romans 12:2, renew your mind, conformity, God\'s will, change, mental renewal',
            createdAt: new Date('2024-12-21').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'Is there a verse about God completing His work in us?',
            answer: 'Philippians 1:6 promises, "And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ." If you have started a journey with God, be encouraged—He will finish what He started. Your transformation is not dependent on your perfection but on God\'s faithfulness to complete His work in you.',
            keywords: 'Philippians 1:6, God completes His work, transformation, faithfulness, good work, perseverance, spiritual growth',
            createdAt: new Date('2024-12-22').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'What Bible verse talks about gaining new strength?',
            answer: 'Isaiah 40:31 encourages, "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint." When you feel exhausted and depleted, God promises to renew your strength as you wait on Him. He gives supernatural strength to keep going even when you feel you cannot.',
            keywords: 'strength, Isaiah 40:31, renewal, waiting on God, endurance, supernatural strength, perseverance, eagles',
            createdAt: new Date('2024-12-23').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            category: 'bible_verses',
            question: 'Is there a verse about doing all things through Christ?',
            answer: 'Philippians 4:13 proclaims, "I can do all things through him who strengthens me." This verse reminds us that we are not alone in our struggles or our calling. Christ gives us the strength to face challenges, overcome obstacles, and accomplish what He has called us to do. With His power working in you, nothing is impossible.',
            keywords: 'Philippians 4:13, strength, Christ strengthens, overcome, empower, possibility, divine power',
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            category: 'forms',
            question: 'How do I apply to the Leadership Development Institute?',
            answer: 'You can apply to the LDI program by completing our LDI Application Form, available on our website at uconministries.org or in person at our office. The application includes questions about your background, current situation, and what you hope to gain from the program. After submission, you will be contacted to schedule an interview with our admissions team.',
            keywords: 'LDI application, apply, enrollment, admissions, Leadership Development Institute, application form, interview',
            createdAt: new Date('2024-12-25').toISOString(),
            updatedAt: new Date('2024-12-25').toISOString(),
        },
        {
            category: 'forms',
            question: 'How can I volunteer at UCon Ministries?',
            answer: 'We would love to have you join our volunteer team! Complete the Volunteer Registration Form on our website or pick one up at our office. The form includes questions about your interests, availability, and skills. After processing your application, our volunteer coordinator will contact you about orientation and available opportunities to serve alongside us.',
            keywords: 'volunteer, registration, serve, opportunities, volunteer form, join the team, getting involved',
            createdAt: new Date('2024-12-26').toISOString(),
            updatedAt: new Date('2024-12-26').toISOString(),
        },
        {
            category: 'forms',
            question: 'How can I make a donation to UCon Ministries?',
            answer: 'Thank you for your generosity! You can donate securely through our Donation Form on our website at uconministries.org, where you can choose to give one-time or set up recurring donations. You can also mail checks to our office at 123 Hope Street, Community Center, CA 90210, or donate in person during business hours. All donations are tax-deductible.',
            keywords: 'donation, giving, contribute, financial support, donate online, tax-deductible, generosity',
            createdAt: new Date('2024-12-27').toISOString(),
            updatedAt: new Date('2024-12-27').toISOString(),
        },
        {
            category: 'forms',
            question: 'How do I submit a prayer request?',
            answer: 'You can submit a prayer request through our Prayer Request Form on our website, call our office, or share your request in person during any of our gatherings. Your request will be lifted up by our prayer team and, if you choose, shared on our prayer wall for the community to pray over. All requests are treated with confidentiality and compassion.',
            keywords: 'prayer request, prayer form, submit prayer, prayer support, prayer team, confidential prayer',
            createdAt: new Date('2024-12-28').toISOString(),
            updatedAt: new Date('2024-12-28').toISOString(),
        },
        {
            category: 'forms',
            question: 'How can I apply to be a mentor?',
            answer: 'If you have experienced transformation and want to walk alongside others on their journey, fill out our Mentorship Application form available on our website or at our office. Mentors go through training and are matched with participants based on backgrounds and needs. This is a powerful way to use your story to bring hope to others.',
            keywords: 'mentorship application, become a mentor, mentoring, peer support, using your story, leadership',
            createdAt: new Date('2024-12-29').toISOString(),
            updatedAt: new Date('2024-12-29').toISOString(),
        },
        {
            category: 'forms',
            question: 'How do I register for workshops?',
            answer: 'Workshop registration is easy! Fill out the Workshop Registration Form on our website, call our office, or simply show up—most workshops welcome walk-ins. The form helps us plan for the right number of materials and seats. All workshops are free and open to the community, so do not hesitate to register and join us.',
            keywords: 'workshop registration, sign up, workshops, register online, free workshops, community programs',
            createdAt: new Date('2024-12-30').toISOString(),
            updatedAt: new Date('2024-12-30').toISOString(),
        },
        {
            category: 'prayers',
            question: 'Does UCon Ministries offer prayer support?',
            answer: 'Yes! We have a dedicated prayer team available 24/7 through our Crisis Hotline at (555) 555-1234. You can also submit written prayer requests through our website, call during business hours, or share requests at any of our gatherings. We believe in the power of prayer and consider it a privilege to intercede on your behalf.',
            keywords: 'prayer support, 24/7 prayer, prayer team, intercession, prayer requests, spiritual support',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            category: 'prayers',
            question: 'How do I submit a prayer request?',
            answer: 'Prayer requests can be submitted through the form on our website, by calling our office at (555) 555-1234, emailing info@uconministries.org, or sharing in person at any event. You can choose to remain anonymous if you prefer. Every request is treated with care, confidentiality, and is prayed over by our faithful prayer team.',
            keywords: 'submit prayer request, prayer, how to request prayer, anonymous prayer, confidential, prayer submission',
            createdAt: new Date('2024-12-02').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        },
        {
            category: 'prayers',
            question: 'What is the prayer wall?',
            answer: 'Our prayer wall is a physical and digital space where community members can share prayer requests and pray for one another. With your permission, your request can be posted on the wall in our facility and on our website, allowing others to join in praying for your situation. It is a beautiful expression of bearing one another\'s burdens as the body of Christ.',
            keywords: 'prayer wall, community prayer, shared requests, praying together, body of Christ, prayer community',
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },
    ];

    await db.insert(chatbotKnowledge).values(sampleKnowledge);
    
    console.log('✅ Chatbot knowledge seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});